- id: coverage-xml
  name: coverage-xml
  language: python
  entry: coverage-xml
  args: []
  pass_filenames: false
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"

- id: coverage-badge
  name: coverage-badge
  language: python
  entry: coverage-badge
  args: []
  pass_filenames: false
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"
