- id: coverage-xml
  name: coverage-xml
  language: script
  entry: coverage-xml.sh
  args: []
  pass_filenames: false

- id: coverage-badge
  name: coverage-badge
  language: script
  entry: coverage-badge.sh
  args: []
  pass_filenames: false
