name: Build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
      - name: Git tag
        run: |
          . install_poetry.sh
          export VERSION=$(poetry version -s)
          git tag -a $VERSION -m "$VERSION release"
          git push origin --tags
