name: Build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
      - name: Git tag
        run: |
          pip install semver
          export VERSION=$(poetry version -s)
          git tag -a $VERSION -m "$VERSION release"
          git push origin --tags
  staging-deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/prerelease')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
      - name: Deploy to PyPi
        run: |
          . install_poetry.sh
          poetry version prerelease
          poetry publish --build -u ${{ secrets.PYPI_USERNAME}} -p ${{ secrets.PYPI_PASSWORD }}
          git commit -a -m "Prerelease bumped version [skip ci]"
          git push
